E_Ticaret_Uygulamasi/Models/Kategoriler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret_Uygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategoriler()
        {
            this.Urunler = new HashSet<Urunler>();
        }
    
        public int KategoriID { get; set; }
        public string KategoriAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}

E_Ticaret_Uygulamasi/Controllers/HomeController.cs
using E_Ticaret_Uygulamasi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Ticaret_Uygulamasi.Controllers
{
    public class HomeController : Controller
    {
        ETicaretVTEntities1 db = new ETicaretVTEntities1();
        public ActionResult Index()
        {
            ViewBag.Kategoriler = db.Kategoriler.ToList();
            ViewBag.Urunler = db.Urunler.OrderByDescending(x=>x.UrunID).Take(10).ToList();
            return View();
        }
        public ActionResult Kategoriler(int id)
        {
           Kategoriler kategori = db.Kategoriler.Find(id);
            ViewBag.KategoriAdi = kategori.KategoriAdi;
            ViewBag.Kategoriler = db.Kategoriler.ToList();
            return View(db.Urunler.Where(x=>x.KategoriID==id).OrderBy(x=>x.UrunAdi).ToList());
        }
        public ActionResult Urun(int id)
        {
            ViewBag.Kategoriler = db.Kategoriler.ToList();
            return View(db.Urunler.Find(id));
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

E_Ticaret_Uygulamasi/Controllers/KategorilerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_Ticaret_Uygulamasi.Models;

namespace E_Ticaret_Uygulamasi.Controllers
{
    [Authorize(Roles ="Admin")]
    public class KategorilerController : Controller
    {
        private ETicaretVTEntities1 db = new ETicaretVTEntities1();

        // GET: Kategoriler
        public ActionResult Index()
        {
            return View(db.Kategoriler.ToList());
        }

        // GET: Kategoriler/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategoriler kategoriler = db.Kategoriler.Find(id);
            if (kategoriler == null)
            {
                return HttpNotFound();
            }
            return View(kategoriler);
        }

        // GET: Kategoriler/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kategoriler/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KategoriID,KategoriAdi")] Kategoriler kategoriler)
        {
            if (ModelState.IsValid)
            {
                db.Kategoriler.Add(kategoriler);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kategoriler);
        }

        // GET: Kategoriler/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategoriler kategoriler = db.Kategoriler.Find(id);
            if (kategoriler == null)
            {
                return HttpNotFound();
            }
            return View(kategoriler);
        }

        // POST: Kategoriler/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KategoriID,KategoriAdi")] Kategoriler kategoriler)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kategoriler).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kategoriler);
        }

        // GET: Kategoriler/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategoriler kategoriler = db.Kategoriler.Find(id);
            if (kategoriler == null)
            {
                return HttpNotFound();
            }
            return View(kategoriler);
        }

        // POST: Kategoriler/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kategoriler kategoriler = db.Kategoriler.Find(id);
            db.Kategoriler.Remove(kategoriler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E_Ticaret_Uygulamasi/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

E_Ticaret_Uygulamasi/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

E_Ticaret_Uygulamasi/Views/Home/Index.cshtml
@using E_Ticaret_Uygulamasi.Models
@{
    ViewBag.Title = "Home Page";

    List<Kategoriler> kategoriListe = ViewBag.Kategoriler as List<Kategoriler>;
    List<Urunler> urunListe = ViewBag.Urunler as List<Urunler>;
}

<div class="jumbotron">
    <h1>ASP.NET MVC E-Ticaret Projesi</h1>
   
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Kategoriler</h2>
        <ul>
            @foreach (var item in kategoriListe)
            {
                <li>
                    @Html.ActionLink(item.KategoriAdi,"Kategoriler",new {id=item.KategoriID })
                </li>
            }
        </ul>
       
    </div>
    <div class="col-md-9">
        <h2>Ürünler</h2>
        
           @foreach (var item in urunListe)
           {
    <div class="col-md-4">
        <h5>@item.UrunAdi</h5>
        <img src="~/Resim/@(item.UrunID).jpg" width="100" height="100" />
        <p>
            <br />
            <a href="@Url.Action("Urun","Home",new {id=item.UrunID })" class="btn btn-warning">Ürün Detay &nbsp;<span style="color:#000000;float:inline-start;">@item.UrunFiyatı TL</span></a>

        </p>
        <br />
    </div>
           }
        
       
    </div>
 
</div>

E_Ticaret_Uygulamasi/Views/Home/Kategoriler.cshtml
@using E_Ticaret_Uygulamasi.Models
@model List<Urunler>
@{
    ViewBag.Title = ViewBag.KategoriAdi;

    List<Kategoriler> kategoriListe = ViewBag.Kategoriler as List<Kategoriler>;
    
}

<div class="jumbotron">
    <h1>ASP.NET MVC E-Ticaret Projesi</h1>

</div>

<div class="row">
    <div class="col-md-3">
        <h2>Kategoriler</h2>
        <ul>
            @foreach (var item in kategoriListe)
            {
                <li>
                    @Html.ActionLink(item.KategoriAdi, "Kategoriler", new { id = item.KategoriID })
                </li>
            }
        </ul>

    </div>
    <div class="col-md-9">
        <h2>Ürünler</h2>

        @foreach (var item in Model)
        {
            <div class="col-md-4">
                <h5>@item.UrunAdi</h5>
                <img src="~/Resim/@(item.UrunID).jpg" width="100" height="100" />
                <p>
                    <br />
                    <a href="@Url.Action("Urun","Home",new {id=item.UrunID })" class="btn btn-warning">Ürün Detay &nbsp;<span style="color:#000000;float:inline-start;">@item.UrunFiyatı TL</span></a>

                </p>
                <br />
            </div>
        }


    </div>

</div>

E_Ticaret_Uygulamasi/Views/Home/Urun.cshtml
@using E_Ticaret_Uygulamasi.Models
@model Urunler
@{
    ViewBag.Title = "Urun";
    List<Kategoriler> kategoriListe = ViewBag.Kategoriler as List<Kategoriler>;
}


<div class="jumbotron">
    <h3>@Model.UrunAdi</h3>

</div>

<div class="col-md-3">
    <h2>Kategoriler</h2>
    <ul>
        @foreach (var item in kategoriListe)
        {
            <li>
                @Html.ActionLink(item.KategoriAdi, "Kategoriler", new { id = item.KategoriID })
            </li>
        }
    </ul>

</div>
<div class="col-md-9">
    <h2><b>Ürün Adı</b></h2>
    <h5>@Model.UrunAdi</h5>
    <div class="row">
        <div class="col-md-6">

            <img src="~/Resim/@(Model.UrunID).jpg" width="100" height="100" />

        </div>
        <div class="col-md-6">

            Ürün Fiyatı:
            &nbsp;<span style="color:#ff0000;float:inline-start;">@Model.UrunFiyatı TL</span>
            <br />
            <form action="/Sepet/SepeteEkle">
                <input type="hidden" value="@Model.UrunID" name="id" id="id"/>
                <input type="number" id="adet " name="adet" value="1" style="width:50px;" min="1" />
                <input type="submit" id="gonder " name="gonder" value="Sepete Ekle" />

            </form>
           

        </div>



    </div>
    <h2>Ürün Açıklaması</h2>
    <p>@Model.UrunAciklamasi</p>
</div>